pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-springboot-app"
        IMAGE_TAG  = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                script {
                    sh "docker-compose down || true"
                    sh "docker-compose up -d --build"
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
    }
}
